### ISSUE TITLE
Transferring ownership of Repo?

### ISSUE THREAD

**Issue by haysclark** [robotlegs/robotlegs-framework#171]
@darscan The fact that robotlegs/robotlegs-framework is forked from  darscan/robotlegs-framework is a bit confusing. Wouldn't it be better to have robotlegs/robotlegs-framework be the root repo by transferring darscan/robotlegs-framework to the robotlegs account?

**Comment by darscan** [comment]
Hi @haysclark. Indeed, I'll see what I can do (I might just delete my repo, and fork from the official)

**Comment by darscan** [comment]
Ouch, that didn't work at all.. now it says it was forked from someone else!

**Comment by darscan** [comment]
All sorted thanks to awesome GitHub staff!
