### ISSUE TITLE
Weakly typed event mapping causes an error when cascading events

### ISSUE THREAD

**Issue by weltraumpirat** [robotlegs/robotlegs-framework#83]
I have a MenuChangeCommand that maps selected menu items to other parts of the system by dispatching new events, that looks something like this:

```
[Inject]
public var myEvent:MenuSelectEvent;

override public function execute() : void {
    if ( myEvent.path == "item1")
        dispatch ( new MenuItemEvent( MenuItemEvent.CALLED ));
} 
```

The EventCommandTrigger throws an error on each of the nested events, since the unnamed and weakly typed mapping of Event around the command execution block in the `handleEvent` method is mapped and unmapped twice,
because the command executions are nested (pseudocode):

```
dispatch MenuSelectEvent
---- map( Event | MenuSelectEvent )
    => execute MenuSelectCommand (dispatch MenuItemEvent)
    ---- map( Event | MenuItemEvent)
         => execute MenuItemCommand
    ---- unmap( Event | MenuItemEvent)
---- unmap( Event | null )   <= Error
```

Error message:

> Error: Error while removing an injector mapping: No mapping defined for dependency flash.events::Event|
>     at org.swiftsuspenders::Injector/unmap() 
> [/Users/till/dev/swiftsuspenders/swiftsuspenders/src/org/swiftsuspenders/Injector.as:218]
>     at robotlegs.bender.extensions.eventCommandMap.impl::EventCommandTrigger/handleEvent()
> [/.../robotlegs-framework/src/robotlegs/bender/extensions/eventCommandMap/impl/EventCommandTrigger.as:130]

**Comment by rexingQ** [comment]
- [ ] 

1. What"($app/src/lib/editors/shared.ts[]()
